<?php

namespace Nycorp\LiteApi\Providers;

use Illuminate\Support\ServiceProvider;

class LiteApiServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->publishes([
            __DIR__.'/../config/lite-api-code.php' => config_path('lite-api-code.php'),
        ]);
    }
}